### PR TITLE
[57-stable] Update SDK to v57 to use hosted bundle

### LINKED ISSUE #64969: SDK reinitializing on each page change (with NextJS pages router)
### Describe the bug

Thanks for all the work on Metabase! I know NextJS particularly is not a primary focus for the team, but I wanted to share an oddity discovered in using the SDK with it in the hope that someone more familiar with the `MetabaseProvider` architecture might be able to shed some light or be able to find a solution.

It seems that when using the Embedding SDK with NextJS applications using the pages router, the SDK is reinitializing on every page change. This introduces 5 network requests (`/auth/sso`, JWT fetch, `/auth/sso?jwt=`, `/api/session/properties`, `/api/user/current`) every time the user navigates. Aside from being noisy and unnecessary, it does make the application feel a little slower; making the user wait a little bit longer for a question or dashboard to load.

See examples from the [metabase-nextjs-sdk-embedding-sample](https://github.com/metabase/metabase-nextjs-sdk-embedding-sample) below.

### Pages Router
https://github.com/user-attachments/assets/a4d54c2e-1cdd-40ea-993f-39505bb43741

### App Router
https://github.com/user-attachments/assets/f3a1c1d1-db67-468c-a5ab-bc7527a5e0fd

_Forgive the missing question/dashboard—this does not seem to affect it._

You can see the reinitializing network requests with the pages router, but not the app router. A couple of other notes:
- The initialization requests succeed each time, successfully authenticating the user and loading its profile
- The JWT and session expire after 10 minutes per the sample app settings, so that does not seem to be the cause
- Both the app and pages router versions of the sample app appear to use the same dynamically-loaded `MetabaseProvider`

In my own app where I also experience this, I verified that NextJS does not seem to be remounting the provider component between page changes (when properly placed in `_app` or similar), so it seems to me like something inside the provider is maybe not memoized correctly or is sensitive to some other change.

### To Reproduce

1. Clone the [metabase-nextjs-sdk-embedding-sample](https://github.com/metabase/metabase-nextjs-sdk-embedding-sample) app
2. Follow [the steps to setup the pages router with an existing Metabase instance](https://github.com/metabase/metabase-nextjs-sdk-embedding-sample?tab=readme-ov-file#manual-run-with-your-existing-metabase-proenterprise-instance)
3. Open the running application in Chrome with DevTools's Network tab open
4. Navigate between pages and see repeated initialization requests each time

### Expected behavior

It should work like the app router — not reinitialize every time the page changes.

### Logs

[localhost-1761248784071.log](https://github.com/user-attachments/files/23107746/localhost-1761248784071.log)

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "postgres",
      "redshift",
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "pro-self-hosted",
    "version": {
      "date": "2025-10-14",
      "tag": "v1.56.10.1",
      "hash": "d7b735e"
    },
    "settings": {
      "report-timezone": "America/New_York"
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "15.12"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.7"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.8+9-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.8",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.8+9-LTS",
    "os.name": "Linux",
    "os.version": "5.10.242-239.961.amzn2.x86_64",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

Experimenting with the SDK; unlikely to use if functioning like this

### Additional context

Many thanks in advance for any assistance!

### PR DESCRIPTION
**Pull request by WiNloSt**
This also fixes https://github.com/metabase/metabase/issues/64969 by not using `/nextjs` export which seems to cause the problem somehow.

This PR does:
1. Update SDK to v57, so we could use hosted bundle
2. That enables us to drop `/nextjs` import

### CODE REVIEW

File: next-sample-app-router/src/app/app-provider.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ if (!process.env.NEXT_PUBLIC_METABASE_INSTANCE_URL) {
 const authConfig = defineMetabaseAuthConfig({
   metabaseInstanceUrl: process.env.NEXT_PUBLIC_METABASE_INSTANCE_URL,
   fetchRequestToken: async () => {
-    const response = await fetch('/api/metabase/auth?response=json', {
+    const response = await fetch("/api/metabase/auth?response=json", {
```
Comment (WiNloSt) [inline next-sample-app-router/src/app/app-provider.tsx:17]: just realized the quotes weren't consistent, so this is fine

File: next-sample-app-router/package-lock.json
Comment (WiNloSt) [inline next-sample-app-router/package-lock.json:1]: changed via `npm install @metabase/embedding-sdk-react@57-stable`

File: next-sample-app-router/package.json [hunk 2]
```diff
@@ -9,7 +9,7 @@
     "lint": "next lint"
   },
   "dependencies": {
-    "@metabase/embedding-sdk-react": "^0.56.5",
+    "@metabase/embedding-sdk-react": "^0.57.0",
```
Comment (WiNloSt) [inline next-sample-app-router/package.json:12]: changed via `npm install @metabase/embedding-sdk-react@57-stable`

File: next-sample-pages-router/package-lock.json
Comment (WiNloSt) [inline next-sample-pages-router/package-lock.json:1]: changed via `npm install @metabase/embedding-sdk-react@57-stable`

File: next-sample-pages-router/package.json [hunk 3]
```diff
@@ -9,7 +9,7 @@
     "lint": "next lint"
   },
   "dependencies": {
-    "@metabase/embedding-sdk-react": "^0.56.5",
+    "@metabase/embedding-sdk-react": "^0.57.0",
```
Comment (WiNloSt) [inline next-sample-pages-router/package.json:12]: changed via `npm install @metabase/embedding-sdk-react@57-stable`

File: readme.md [hunk 4]
```diff
@@ -1,14 +1,14 @@
...
+>
 > **To spin up a new Metabase**, you can use any version branch and run the sample app in the [Docker container](#run-both-apps--a-sample-metabase-proenterprise-instance-in-docker) with the corresponding version of Metabase. You'll need a Pro/Enterprise token, which you can get with a [free trial of Pro](https://www.metabase.com/pricing/)..
 
 # Metabase Embedding React SDK nextjs sample apps
 
 This repository contains sample apps for Next.js 14 that uses Metabase Embedding SDK.
 It includes an app using pages router and an app using the app router.
 
-Note: the samples are using the sdk Next.js compatibility layer, which is available from version 0.51.11.
+Note: Please use Metabase version 57 or above to test these sample apps.
```
Comment (WiNloSt) [inline readme.md:11]: I don't think we need to mention nextjs exports anymore.

**Review by sanex3339 — DISMISSED** [review]
Please update metabase instance version in docker-compose files

File: docker-compose.yml [hunk 5]
```diff
@@ -11,7 +11,7 @@ services:
       MB_PREMIUM_EMBEDDING_TOKEN: "${PREMIUM_EMBEDDING_TOKEN}"
       MB_RUN_MODE: "${MB_RUN_MODE}"
       METASTORE_DEV_SERVER_URL: "${METASTORE_DEV_SERVER_URL}"
-      MB_JWT_IDENTITY_PROVIDER_URI: "http://localhost:${AUTH_PROVIDER_PORT}/sso/metabase"
+      MB_JWT_IDENTITY_PROVIDER_URI: "http://unused.com/sso/metabase"
```
Comment (WiNloSt) [inline docker-compose.yml:14]: I suspect this env variable has been removed for a while. So I changed it to reflect that this value isn't really used as we set `fetchRequestToken`.
https://github.com/metabase/metabase-nextjs-sdk-embedding-sample/blob/16af3fa8e7d70a4a05e2c414fa156effdc8548cb/next-sample-app-router/src/app/app-provider.tsx#L16-L20

We still require it to be set, though.

You can see [on the CI](https://github.com/metabase/metabase-nextjs-sdk-embedding-sample/actions/runs/20489143861/job/58877663796#step:3:16) that this variable hasn't been set.

> time="2025-12-24T15:25:16Z" level=warning msg="The \"AUTH_PROVIDER_PORT\" variable is not set. Defaulting to a blank string."

**Review by sanex3339 — APPROVED** [review]
